# build environment
FROM node:16-alpine as build
WORKDIR /app


ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production environment
FROM caddy:2
COPY --from=build /app/build /usr/share/caddy
EXPOSE 80 443
