FROM node:18

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y build-essential

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package.json ./
COPY package-lock.json ./

# Instala las dependencias de Node.js
RUN npm install

# Copia el resto de la aplicación
COPY . ./

# Cambia la propiedad de los archivos al usuario `node`
RUN chown -R node:node /app

# Cambia el usuario a no-root
USER node

# Inicia la aplicación
CMD ["npm", "run", "dev"]