FROM node:18

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y build-essential

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package.json ./
COPY package-lock.json ./

# Copia el resto de la aplicación
COPY . ./

# Instala las dependencias de Node.js
RUN npm install

# Inicia la aplicación
CMD ["npm", "run", "dev"]